// test.http
@url=http://zhoujiazhao:3344

### 
get {{url}}/users

###
POST {{url}}/users/register HTTP/1.1
Content-Type: application/json

{
    "username":"zhoujiazhao",
    "password":"xxxxxxxxxxxxxx"
}

###
POST {{url}}/users/login HTTP/1.1

{
    "username":"zhoujiazhao",
    "password":"xxxxxxxxxxxxxx"
}